### ISSUE TITLE
Passare valori nulli nella query per User Contributions

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#14]
Attualmente le API `/api/{id}/file/upload-date-all` e `/api/{id}/file/upload-date` non passano i dati con valore zero.

Bisognerebbe passare anche quelli con valore a 0 in modo da avere una rappresentazione veritiera sul bar chart.

@diegmonti

**Comment by diegmonti** [comment]
Fatto per `upload-date-all`. Con `upload-date` non cambierebbe la visualizzazione, visto che è già presente il totale.

**Comment by francescocretti** [comment]
Perfetto!
