### ISSUE TITLE
Diverse granularità per User Contributions

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#15]
Rendere la query parametrica per la granularità con cui aggregare i dati delle user contributions.

In particolare servirebbe:
- mese (come attuale);
- trimestre;
- anno;

**Comment by diegmonti** [comment]
Aggiunto un parametro `groupby` che accetta come valori:
* month
* quarter
* year

**Comment by francescocretti** [comment]
Ottimo, inserita l'opzione nel front-end.
Funziona bene!
Grazie @diegmonti
