### ISSUE TITLE
Formato download dataset

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#17]
Ci hanno chiesto di aggiungere un'opzione di scelta del formato di download: oltre a JSON aggiungere il CSV.

@diegmonti con @alemela stavam discutendo se fosse meglio farlo lato front-end o back-end. Tu cosa ne dici?

**Comment by diegmonti** [comment]
Credo sia meglio farlo lato back-end. Tuttavia bisogna capire il formato dei CSV e quali dati includere: l'unico ovvio è quello delle views globali.

**Comment by alemela** [comment]
Partirei solo con i valori di sintesi, giusto per fargli vedere che un CSV c'è. Ovviamente il dato completo è complesso o pesante. Quindi per ogni vista possiamo dare una specie di corrispettivo del menu laterale destro come CSV.

Credo sia quello che si aspettano e non è troppo gravoso. Non c'è una vera esigenza dietro...

Se serve, valutiamo insieme lo schema la prossima volta.
