### ISSUE TITLE
API per dettagli sul singolo file

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#22]
Servirebbe un API (una cosa tipo `/api/{glam}/file/details/{file}`)  per ottenere i seguenti dati, per ogni file:

- URL immagine su commons;
- statistiche sulle views sul singolo file (tot, avg, median);
- lista delle categorie in cui è contenuta l'immagine;

Così posso completare la pagina "interoperabilità"

**Comment by diegmonti** [comment]
L'URL dell'immagine si può ottenere lato frontend usando questa API: `https://commons.wikimedia.org/w/api.php?action=query&format=json&iiprop=url&prop=imageinfo&titles=File:Albert_Einstein_Head.jpg`.

A partire dall'URL ottenuto si può costruire un altro URL per ottenere la versione riscalata dell'immagine: `https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/180px-Albert_Einstein_Head.jpg`. Il valore prima di px è modificabile a piacere.

**Comment by francescocretti** [comment]
Ok perfetto, grazie @diegmonti

**Comment by diegmonti** [comment]
Rettifica, bisogna usare un URL simile a questo: `http://commons.wikimedia.org/wiki/Special:FilePath/Kantonales naturhistorisches Museum (Gebäude) 2013-09-17 17-08-17.jpg`.

Si ottiene un redirect alla versione full dell'immagine da cui può creare il link per la versione riscalata.
