### ISSUE TITLE
API /usage/file restituiscono array vuoto per immagini TIFF

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#24]
Ad esempio ``http://localhost:8081/api/ZU/usage/file/Zentralbibliothek_Solothurn_-_Schweizerische_Hauptkirchen_-_aa0050.tiff``

**Comment by francescocretti** [comment]
Rettifico, non è questione dei TIFF, ad esempio qui funziona tutto:

`http://localhost:8081/ZU/file/Rennwegtor_Edlibach.tiff`

**Comment by diegmonti** [comment]
Il vettore è vuoto perché quel file non è utilizzato in nessuna pagina.

**Comment by alemela** [comment]
Grazie @diegmonti, in effetti non avevamo ancora gestito tutti i casi margine. Nei prossimi giorni nel preparare la documentazione ci faccio particolare caso se ne trovo altri.
