### ISSUE TITLE
Modifiche alle API per le annotazioni

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#28]
Ciao @diegmonti .
Avrei bisogno di alcune modifiche alle API per le annotazioni. In particolare:
- l'API che restituisce l'elenco di tutte le annotazioni (`/admin/glams/{glam}/annotations`) dovrebbe essere aperta e non sotto admin;
- le altre (aggiungi, elimina, modifica), rimangono sotto admin;
- dovremmo trovare un modo per consentire all'utente di autenticarsi quando vuole entrare nella modalità *edita annotazioni*; ad esempio una API /`/api/admin/auth`. Ti sembra sensato?
- l'oggetto annotazione dovrebbe avere più campi, in particolare come questo:
```
{
  "data": "2018-07-18",
  "value": 40000,
  "position": "left"
}
```

**Comment by diegmonti** [comment]
Ho aggiunto la posizione all'annotazione con 15625a4.
