### ISSUE TITLE
Le statistiche delle views del singolo file sono sbagliate

### ISSUE THREAD

**Issue by giorgiobevilacqua** [synapta/cassandra-GLAM-tools#31]
[Cfr mail di segnalazione di Debora Lopomo]

La mediana delle VIEWS STATS indica 7, ma il grafico non scende mai sotto le 100 views: 

https://stats.wikimedia.swiss/SNL/file/CH-NB_-_Pissevache,_Cascade_de_-_Collection_Gugelmann_-_GS-GUGE-MECHEL-C-4.tif 

Non so se il problema si ripete anche per le statistiche delle views della categoria complessiva

**Comment by diegmonti** [comment]
Il grafico mostra il numero di visualizzazioni aggregate per mese, mentre le statistiche nella barra laterale sono calcolate per giorno. Le visualizzazioni della categoria complessiva presenti nel grafico sono invece aggregate per settimana.
