### ISSUE TITLE
README.md and documentation shortcomings

### ISSUE THREAD

**Issue by fuzheado** [synapta/cassandra-GLAM-tools#54]
Does the README.md provide enough documentation to install the system from scratch? For example:

"Copy the file config/config.example.json to config/config.json and modify it as required."

This seems like there's a lot that needs to be done here in terms of database setup, and I'm not sure what the right directions would be here. Thanks.

**Comment by alemela** [comment]
Thanks @fuzheado for your comment! We will update the documentation soon with more details.
